### ISSUE TITLE
「1.3 始める前に」のソースコードの準備について

### ISSUE THREAD

**Issue by genkiFurukawa** [vuejs-kaibou/vue3_kaitai_shinsho_suppport#1]
業務でvue3を急遽使うことになり、本書籍を購入させていただきました。本書を休みの日に読んで業務に臨み、何とか山場を越えることができました。ありがとうございます。業務が落ち着いたので、ソースコードもちゃんと読もうと思い始めているところです。

前置きが長くなってしまいましたが、ソースコードの準備について教えていだだけないでしょうか？
下記の手順を実行すると、エラーが出ます。nodeのバージョンはv16.13.1、yarnのバージョンは1.22.17です。

```
$ git clone https://github.com/vuejs/vue-next.git
$ cd vue-next
$ yarn install

This repository requires using pnpm as the package manager  for scripts to work properly.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

`yarn install --ignore-scripts`を実行すると、エラーがvue-nextのプロジェクトのビルドができる（言い方正しいでしょうか？）ように見受けられます。定義ジャンプができるので問題なさそうに見えるのですが、手順として問題ないでしょうか？

初心者質問で申し訳ありませんが、ご確認いただけると幸いです。よろしくお願いします。

**Comment by taiyop** [comment]
@genkiFurukawa 
ご質問ありがとうございます。

github.com/vuejs/vue-next
こちら今は下記URLにリダイレクトされるようになっておりますね。
https://github.com/vuejs/core

上記githubページやいただいたyarn installの実行結果を読むと、今はパッケージマネージャーにnpmではなくpnpmを使っているようです。

<img width="907" alt="image" src="https://user-images.githubusercontent.com/1048048/153740021-e64dcaab-0234-458f-97e5-600693629f27.png">

下記、メンバーの @tooppoo に調べてもらった情報です。yarnではなく、pnpmをつかってinstallすると解決しないでしょうか？
https://github.com/vuejs/core/pull/4766
https://zenn.dev/hibikine/articles/27621a7f95e761#pnpm

**Comment by genkiFurukawa** [comment]
ご教示いただいたpnpmをインストールし、下記の手順を踏んだところエラーなくプロジェクトのビルドができました。ご確認いただきありがとうございました。

```
$ curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
$ pnpm i
```
